-- Oracle Database Schema Creation Script
-- Suitable for Oracle 12c+ / 19c / 21c / 23c

CREATE TABLE app_users (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password_hash VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    phone_number VARCHAR2(30),
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    failed_login_attempts NUMBER(3, 0) DEFAULT 0 NOT NULL,
    account_locked NUMBER(1, 0) DEFAULT 0 NOT NULL,
    password_expires_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE app_roles (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE app_user_roles (
    user_id NUMBER(19, 0) NOT NULL,
    role_id NUMBER(19, 0) NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES app_roles(id) ON DELETE CASCADE
);

CREATE TABLE payment_transactions (
    transaction_id VARCHAR2(64) PRIMARY KEY,
    gateway_reference VARCHAR2(128),
    provider VARCHAR2(30) NOT NULL,
    amount NUMBER(19, 4) NOT NULL,
    currency VARCHAR2(10) NOT NULL,
    status VARCHAR2(30) NOT NULL,
    handler_id VARCHAR2(64),
    customer_id VARCHAR2(64),
    message VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Default Roles and Admin User Seed
INSERT INTO app_roles (role_name) VALUES ('ROLE_ADMIN');
INSERT INTO app_roles (role_name) VALUES ('ROLE_USER');

INSERT INTO app_users (username, password_hash, email, first_name, last_name, status, password_expires_at)
VALUES ('admin', '$2a$10$e8q4R0Hh5mQ9V9/lX8M27eWwB1P6i1Kk.R9X5s4O6U5h4k3j2l1i.', 'admin@cthjob.com', 'System', 'Admin', 'ACTIVE', SYSDATE + 90);

INSERT INTO app_user_roles (user_id, role_id)
VALUES ((SELECT id FROM app_users WHERE username = 'admin'), (SELECT id FROM app_roles WHERE role_name = 'ROLE_ADMIN'));

COMMIT;
